package com.xartifex.simplequiz.rest;

public enum Error {
    GAME_NOT_STARTED_YET,
    GAME_ALREADY_FINISHED,
    TIMEOUT_EXPIRED,
    QUESTION_ALREADY_ANSWERED,
    UNKNOWN_COMMAND,
    UNEXPECTED_ERROR,
    CURRENT_QUESTION_NOT_ANSWERED,
    INCORRECT_QUESTION_ID_PROVIDED,
    EMPTY_ANSWER_PROVIDED,
    NOTHING_TO_ANSWER_YET

}
